begin tran

CREATE TABLE [LP_Configuration].[LPInternalError](
	[idLPInternalError] [LP_Common].[LP_I_UNIQUE_IDENTIFIER_INT] IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[Code] [LP_Common].[LP_F_CODE] NOT NULL,
	[Name] [LP_Common].[LP_F_NAME] NOT NULL,
	[Description] LP_Common.[LP_F_DESCRIPTION] NOT NULL,
	[Active] LP_Common.LP_A_ACTIVE NOT NULL
);

CREATE TABLE [LP_Configuration].[LPInternalStatusClient](
	idInternalStatus LP_Common.LP_I_UNIQUE_IDENTIFIER_INT NOT NULL,
	idLPInternalError LP_Common.LP_I_UNIQUE_IDENTIFIER_INT NOT NULL,
	PRIMARY KEY(idInternalStatus, idLPInternalError)
);


INSERT INTO LP_Configuration.LPInternalError(Code, Name, Description, Active) 
VALUES
	('700', 'ERROR BANK ACCOUNT INCORRECT', 'ERROR BANK  ACCOUNT INCORRECT', 1),
	('701', 'ERROR BANK ACCOUNT CLOSED', 'ERROR BANK ACCOUNT CLOSED', 1),
	('702', 'ERROR AMOUNT INCORRECT', 'ERROR AMOUNT INCORRECT', 1),
	('703', 'ERROR BANK INVALID', 'ERROR BANK INVALID', 1),
	('704', 'ERROR BANK BRANCH INCORRECT', 'ERROR BANK BRANCH INCORRECT', 1),
	('705', 'ERROR BENEFICIARY DOCUMENT ID INVALID', 'ERROR BENEFICIARY DOCUMENT ID INVALID', 1),
	('706', 'ERROR BENEFICIARY NAME INCORRECT', 'ERROR BENEFICIARY NAME INCORRECT', 1),
	('707', 'ERROR BANK PROCESSING', 'ERROR BANK PROCESSING', 1),
	('708', 'ERROR INVALID DATE', 'ERROR INVALID DATE', 1),
	('709', 'ERROR ACCOUNT TYPE INCORRECT', 'ERROR ACCOUNT TYPE INCORRECT', 1),
	('710', 'ERROR ACCOUNT NOT MATCH BENEFICIARY DOCUMENT', 'ERROR ACCOUNT NOT MATCH BENEFICIARY DOCUMENT', 1),
	('711', 'ERROR ACCOUNT NOT MATCH BENEFICIARY NAME', 'ERROR ACCOUNT NOT MATCH BENEFICIARY NAME', 1),
	('712', 'ERROR AMOUNT EXCEEDS BENEFICIARY MAX LIMIT', 'ERROR AMOUNT EXCEEDS BENEFICIARY MAX LIMIT', 1),
	('713', 'ERROR ACCOUNT NOT ACCEPT TRANSFERS', 'ERROR ACCOUNT NOT ACCEPT TRANSFERS', 1),
	('714', 'ERROR BENEFICIARY DOCUMENT DOES NOT MATCH NAME', 'ERROR BENEFICIARY DOCUMENT DOES NOT MATCH NAME', 1),
	('715', 'ERROR ACCOUNT OF OTHER CURRENCY', 'ERROR ACCOUNT OF OTHER CURRENCY', 1),
	('716', 'ERROR REJECTED BY COMPLIANCE', 'ERROR REJECTED BY COMPLIANCE', 1),
	('717', 'ERROR REJECTED BENEFICIARY BLACKLISTED', 'ERROR REJECTED BENEFICIARY BLACKLISTED POST APPROVAL', 1)

	
commit tran
