INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('138','40138','ABC CAPITAL');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('614','90614','ACCIVAL');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('133','40133','ACTINVER');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('062','40062','AFIRME');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('678','90678','AFORE SURA');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('638','90638','AKALA');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('103','40103','AMERICAN EXPRES');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('652','90652','ASEA');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('659','90659','ASP INTEGRA OPC');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('128','40128','AUTOFIN');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('674','90674','AXA');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('127','40127','AZTECA');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('030','40030','BAJIO');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('106','40106','BAMSA');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('002','40002','BANAMEX');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('131','40131','BANCO FAMSA');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('006','37006','BANCOMEXT');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('137','40137','BANCOPPEL');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('152','40152','BANCREA');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('019','37019','BANJERCITO');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('147','40147','BANKAOOL');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('009','37009','BANOBRAS');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('072','40072','BANORTE/IXE');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('058','40058','BANREGIO');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('166','37166','BANSEFI');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('060','40060','BANSI');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('001','2001','BANXICO');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('129','40129','BARCLAYS');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('610','90610','B&B');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('145','40145','BBASE');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('012','40012','BBVA BANCOMER');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('812','91812','BBVA BANCOMER2');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('112','40112','BMONEX');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('132','40132','BMULTIVA');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('691','90691','BTG PACTUAL');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('677','90677','CAJA POP MEXICA');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('683','90683','CAJA TELEFONIST');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('621','90621','CB ACTINVER');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('626','90626','CBDEUTSCHE');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('630','90630','CB INTERCAM');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('640','90640','CB JPMORGAN');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('143','40143','CIBANCO');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('631','90631','CI BOLSA');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('901','90901','CLS');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('130','40130','COMPARTAMOS');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('140','40140','CONSUBANCO');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('126','40126','CREDIT SUISSE');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('680','90680','CRISTOBAL COLON');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('124','40124','DEUTSCHE');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('151','40151','DONDE');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('606','90606','ESTRUCTURADORES');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('648','90648','EVERCORE');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('616','90616','FINAMEX');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('634','90634','FINCOMUN');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('679','90679','FND');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('689','90689','FOMPED');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('685','90685','FONDO (FIRA)');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('149','40149','FORJADORES');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('601','90601','GBM');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('673','90673','GNP');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('636','90636','HDI SEGUROS');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('168','37168','HIPOTECARIA FED');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('021','40021','HSBC');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('821','91821','HSBC2');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('671','90671','HUASTECAS');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('036','40036','INBURSA');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('902','90902','INDEVAL');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('687','90687','INFONAVIT');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('150','40150','INMOBILIARIO');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('037','40037','INTERACCIONES');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('136','40136','INTERCAM BANCO');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('686','90686','INVERCAP');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('102','40102','INVESTA BANK');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('059','40059','INVEX');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('110','40110','JP MORGAN');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('653','90653','KUSPIT');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('670','90670','LIBERTAD');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('619','90619','MAPFRE');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('602','90602','MASARI');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('615','90615','MERRILL LYNCH');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('042','40042','MIFEL');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('600','90600','MONEXCB');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('135','37135','NAFIN');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('622','90622','OACTIN');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('637','90637','ORDER');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('649','90649','OSKNDIA');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('148','40148','PAGATODO');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('682','90682','PERSEVERANCIA');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('681','90681','PRINCIPAL');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('620','90620','PROFUTURO');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('642','90642','REFORMA');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('156','40156','SABADELL');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('014','40014','SANTANDER');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('044','40044','SCOTIABANK');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('651','90651','SEGMTY');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('623','90623','SKANDIA');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('655','90655','SOFIEXPRESS');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('646','90646','STP');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('108','40108','TOKYO');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('139','40139','UBS BANK');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('656','90656','UNAGRA');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('617','90617','VALMEX');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('605','90605','VALUE');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('608','90608','VECTOR');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('113','40113','VE POR MAS');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('141','40141','VOLKSWAGEN');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('134','40134','WAL-MART');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('627','90627','ZURICH');
INSERT INTO [LP_Configuration].[RelationInicioClabeParticipante] (INICIOCLABE, PARTICIPANTE, CLABE) VALUES ('628','90628','ZURICHVI');
