BEGIN TRAN

CREATE TABLE [LP_Operation].[ProviderFileControl](
idProviderFileControl [LP_Common].[LP_I_UNIQUE_IDENTIFIER_INT] IDENTITY(1,1) PRIMARY KEY,
idProvider [LP_Common].[LP_I_UNIQUE_IDENTIFIER_INT],
FileControlNumber BIGINT NOT NULL,
[OP_InsDateTime] [LP_Common].[LP_A_OP_INSDATETIME] NOT NULL DEFAULT GETDATE(),
[OP_UpdDateTime] [LP_Common].[LP_A_OP_UPDDATETIME] NOT NULL DEFAULT GETDATE(),
[DB_InsDateTime] [LP_Common].[LP_A_DB_INSDATETIME] NOT NULL DEFAULT GETDATE(),
[DB_UpdDateTime] [LP_Common].[LP_A_DB_UPDDATETIME] NOT NULL DEFAULT GETDATE(),
)
COMMIT TRAN