CREATE TYPE [LP_Operation].[Referencias_Id] AS TABLE(
	[IDX] [LP_Common].[LP_I_UNIQUE_IDENTIFIER_INT] IDENTITY(1,1) NOT NULL,
	[idNew] [LP_Common].[LP_I_UNIQUE_IDENTIFIER_INT] NOT NULL,
	[TempId] [LP_Common].[LP_I_UNIQUE_IDENTIFIER_INT] NOT NULL
)
GO


